name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  deploy-test-server:
    runs-on: ['test-server']

    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run ci

